module.exports = 

['nauczyciel', 'lekarz', 'uczeń', 'shrek', 'siłacz', 'pływanie', 'siatkówka', 'kot', 'pies', 'rejs', 'czarny charakter', 'znachor',
    'chwycić byka za rogi', 'złego diabli nie biorą', 'vabank', 'egipskie ciemności', 'strzał w dziesiątkę', 'pan tadeusz', 'absolwent',
    'życie za życie', 'galerianki', 'nie dolewaj oliwy do ognia', 'rewers', 'róża', 'pamiętnik', 'porachunki', 'napad', 'policjant', 'pianista',
    'tron', 'król', 'żaba', 'rower', 'szkoła', 'internet', 'gra', 'komiks', 'szeryf', 'fikołek', 'salto', 'zakaz parkowania', 'lewa noga', 'wizytówka',
    'walka kogutów', 'stolarz', 'dziurawe ręce', 'blizna', 'amputacja', 'kolorowe sny', 'paluszek', 'chodząca encyklopedia', 'gwiazdozbiór',
    'blada twarz', 'szlaban', 'taniec', 'grzywka', 'drwal', 'białe na czarnym', 'mieć w małym palcu', 'kasjer', 'bramkarz', 'kotlet', 'hamburger',
    'opaska', 'ciągnik', 'liczydło', 'skrzypek', 'telewizor', 'szelki', 'orzech', 'cytryna', 'zarost', 'fajtłapa', 'daleki wschód', 'dywan',
    'środek dopingujący', 'myśliwy', 'globus', 'rogi', 'radar', 'aplauz', 'krawcowa', 'świniopas', 'dynamit', 'ufo', 'dioda', 'zapach', 'recepta',
    'uśmiech', 'chłop jak dąb', 'kątomierz', 'domino', 'deska do prasowania', 'randka', 'łaskotki', 'instrumenty szarpane', 'bałwan', 'festiwal',
    'kąt prosty', 'papuga', 'szambo', 'kąpiel', 'boisko', 'papierek', 'balet', 'treser', 'półwysep', 'haczyk', 'atrament', 'nadwaga', 'namiot',
    'drużyna', 'łyżwa', 'iść jak krew z nosa', 'hotdog', 'trzymać kciuki', 'świadectwo', 'klej', 'stanie na głowie', 'rybak', 'luneta', 'śmierć',
    'jaskinia', 'wynik', 'siarka', 'cuda na kiju', 'serduszko', 'pępek', 'suwak', 'korzeń', 'wakacje', 'śmieci', 'szpara', 'kanapka', 'trąba', 'pióro',
    'konduktor', 'słupek', 'siekiera', 'pacjentka', 'kurczak', 'rolnik', 'nauczyciel', 'biurko', 'ramka', 'akademik', 'suszarka', 'klaun', 'mnożenie',
    'filtr', 'sumo', 'koperta', 'mapa polski', 'chrupki', 'flaga', 'tornado', 'sandał', 'szafka', 'szpieg', 'żyrafa', 'bajka', 'wampir', 'fosa', 'anonim',
    'szabla', 'podatek', 'fale radiowe', 'iloczyn', 'fotografia', 'bariera', 'tapeta', 'sierp i młot', 'jajko na twardo', 'szofer', 'kapeć', 'całus',
    'rondo', 'pistolet', 'paliwo', 'kurtka', 'fala', 'banknot', 'mandat', 'unik', 'kostka', 'siostra', 'kozak', 'szalik', 'koparka', 'smoczek', 'kant',
    'bunkier', 'jedzenie', 'biegunka', 'cegielnia', 'mleczarnia', 'okulary', 'kowboj', 'szklarnia', 'stopa', 'armata', 'baton', 'język obcy', 'peron',
    'masło', 'ramię', 'czołg', 'skakanka', 'krata', 'cylinder', 'giełda', 'futerał', 'zapalnczka', 'papieros', 'sufit', 'eksplozja', 'forteca', 'imadło',
    'przycisk', 'hipnoza', 'dojazd', 'ukryta kamera', 'dziupla', 'czepek', 'słońce', 'kręgielnia', 'rzeka', 'środek', 'małe piwo', 'grzejnik',
    'amunicja', 'list gończy', 'dodawanie', 'grzebień', 'czapka z daszkiem', 'zęby mleczne', 'kamień węgielny', 'dłoń', 'cena', 'notes', 'podbrzusze',
    'antybiotyk', 'mikrofon', 'zakup', 'rękawice bokserskie', 'sedes', 'zakazany owoc', 'szczoteczka', 'pościel', 'suchar', 'pionek', 'burza śnieżna',
    'trawa', 'wieszak', 'pierścień', 'wyścig szczurów', 'strajk', 'dobranocka', 'pasta do zębów', 'miniaturka', 'proszek', 'przeładunek', 'echo',
    'pokrętło', 'kajak', 'robak', 'wagon', 'bułka z masłem', 'latawiec', 'ucho', 'klamka', 'drogi oddechowe', 'gnojówka', 'temperówka', 'morskie oko',
    'nurek', 'warszawa', 'mur', 'cygan', 'policzek', 'maskotka', 'skrzypce', 'tlen', 'skok w dal', 'kocie łby', 'papier toaletowy', 'francja',
    'drogowskaz', 'kaptur', 'szufelka', 'margines', 'szef kuchni', 'żyłka', 'biała broń', 'pół biedy', 'wstęga', 'mleko', 'klatka', 'detektyw',
    'załoga', 'gonitwa', 'kieszeń', 'sędzia', 'obraz', 'skłon', 'czytelnik', 'wieżowiec', 'papieros elektroniczny', 'meksykanin', 'zaspa', 'pajęczyna',
    'trzepaczka', 'krótkowidz', 'ścieżka', 'nałóg', 'celnik', 'cyrkiel', 'gosposia', 'poślizg', 'krawiec', 'biedak', 'drukarka', 'bazyliszek', 'marchew',
    'równik', 'lada', 'gorzelnia', 'pirat', 'gablota', 'burdel na kółkach', 'jabłko', 'radiowóz', 'cennik', 'koniec', 'przecinek', 'szpilki', 'symbol',
    'izba wytrzeźwień', 'kurtyna', 'klasówka', 'limuzyna', 'skóra', 'drops', 'podbite oko', 'lotnia', 'wiatrak', 'karawana', 'teleskop',
    'krem do golenia', 'poprzeczka', 'wiatr', 'komputer', 'łapówka', 'piwnica', 'rzut oszczepem', 'rower górski', 'dekoracja', 'klocek', 'wiadro',
    'kropka', 'galeria', 'drut', 'brzytwa', 'kolorowanka', 'stanik', 'cebula', 'pogotowie', 'anglia', 'listonosz', 'torebka', 'działka', 'odpowiedź',
    'żółw', 'winda', 'kąt', 'sypialnia', 'sukces', 'plebania', 'mały włos', 'grzywa', 'odpoczynek', 'kibic', 'bezrobotny', 'plecak', 'kolekcja',
    'rakieta', 'kryjówka', 'fusy', 'kulig', 'afryka', 'gratulacje', 'biwak', 'dialog', 'strażak', 'pokłon', 'przewodnik', 'obsługa', 'biblioteka',
    'dodatek', 'klatka schodowa', 'błotnik', 'pierwsza dama', 'lemoniada', 'korek', 'flakon', 'trener', 'dyskietka', 'znak zapytania', 'kilof',
    'jubiler', 'dworzec', 'tatuaż', 'bank', 'sowa', 'zakopane', 'murzyn', 'ogniwo', 'animacja', 'eliminacja', 'kamerzysta', 'struna', 'torba', 'tytoń',
    'kiosk', 'tancerka', 'sakiewka', 'malarz', 'psia kość', 'encyklopedia', 'podpis', 'ogryzek', 'puchar', 'domena', 'koło ratunkowe', 'suchy chleb',
    'cel', 'baba jaga', 'rzut beretem', 'motyle w brzuchu', 'pień', 'głos', 'numer', 'spóźnienie', 'parking', 'komiks', 'komis', 'higiena', 'kafelek',
    'siatkówka', 'pętelka', 'bliźniak', 'obiad', 'motyl', 'ograniczenie prędkości', 'tenis ziemny', 'kalesony', 'pomidor', 'szatnia', 'spódniczka',
    'filharmonia', 'paznokieć', 'prześwietlenie', 'kierownica', 'katechetka', 'wybuch płaczu', 'babie lato', 'dymisja', 'apteka', 'pilot', 'reklama',
    'struny głosowe', 'zegarek', 'pokrzywa', 'ameryka', 'cicha woda', 'lalka', 'kimono', 'asystent', 'obrona', 'komunikacja', 'plansza',
    'płyn do mycia naczyń', 'gwizd', 'przeprowadzka', 'piętro', 'packa', 'miska', 'słoń trąbalski', 'pogoda', 'katastrofa', 'krawat', 'pudernica',
    'tłusty czwartek', 'skok w bok', 'jądro atomowe', 'oczko w głowie', 'bezczynność', 'czerwone gitary', 'lwia część', 'związek partnerski',
    'samolot pasażerski', 'światło', 'kleszcze', 'barka', 'przyprawa', 'śmieciarz', 'grabie', 'lewitacja', 'układanka', 'jasność', 'fajerwerki',
    'piwo', 'wódka', 'wino', 'spływ kajakowy', 'pogrzeb', 'pieczątka', 'indyk', 'magnez', 'geometria', 'zapałka', 'przejście', 'pociąg', 'żądło',
    'maska', 'latarnia morska', 'rozporek', 'zderzak', 'typowy janusz', 'konstytucja', 'zwrot', 'myszka miki', 'trawnik', 'szpon', 'wzrok', 'nawias',
    'żagiel', 'pompka', 'grobowiec', 'huśtawka', 'redukcja', 'tłumacz', 'przerwa', 'biała śmierć', 'zachód', 'polowanie', 'ropucha', 'włos', 'odcisk',
    'kamil', 'kiep', 'sierp', 'skarpety', 'baltona', 'władek', 'ruski', 'kubek', 'piosenka', 'mebloscianka', 'amarena', 'górnik', 'materac', 'narkotyki',
    'kokaina', 'heroina', 'kebab', 'kolano', 'bicie serca', 'elementarz', 'cygar', 'grzmot', 'zwrotnik', 'trójmiasto', 'komar', 'gwiezdne wojny',
    'marsz', 'egzekucja', 'talerz', 'łuska', 'pocisk', 'żołnierz', 'bal sylwestrowy', 'chmiel', 'bateria', 'pacjent', 'instrukcja', 'pianka do golenia',
    'cygaro', 'wjazd', 'ostatni grosz', 'dynia', 'ścieżka dźwiękowa', 'wyskok', 'mysz', 'makaron włoski', 'pizza', 'brew', 'powstanie',
    'ostatnie słowo', 'dziczyzna', 'dron', 'przejście graniczne', 'bezludna wyspa', 'elektrownia wodna', 'pięta', 'procesor', 'wojna domowa',
    'junior', 'koronka', 'woda święcona', 'koryto', 'hipopotam', 'placki', 'burza', 'papież', 'adwokat', 'sędzia', 'prokurator', 'saper', 'konewka',
    'opiekun', 'ciężarówka', 'jajecznica', 'ubaw po pachy', 'nadawca', 'szklany sufit', 'wydech', 'hokej', 'zimne ognie', 'żółwik', 'walec',
    'lotnisko', 'jaszczurka', 'czerwona kapusta', 'tort urodzinowy', 'wywiad', 'trąbka', 'czołowe zderzenie', 'hasło', 'brat', 'karzeł',
    'kamikadze', 'kierunek', 'zakrętka', 'warzywo', 'owoc', 'telefon', 'ogłoszenie', 'mikrofalówka', 'rękawiczka', 'karetka', 'alkohol', 'równowaga',
    'dobry duch', 'koszula', 'zegar słoneczny', 'brudas', 'kameleon', 'paproć', 'stoper', 'fortuna', 'farmer', 'kelner', 'saksofon', 'flaki',
    'klonowanie', 'spotkanie', 'sztylet', 'podkolanówki', 'dziura', 'mieć klapki na oczach', 'flamaster', 'banan', 'fortepian', 'geniusz',
    'pocałować klamkę', 'rozlew krwi', 'podział', 'radiostacja', 'japonki', 'kino', 'teatr', 'klips', 'piegi', 'piksel', 'antena satelitarna',
    'pierogarnia', 'konik morski', 'wąskie gardło', 'klasa', 'latający talerz', 'basen', 'reakcja', 'błyskawica', 'agresja', 'wielki brat',
    'kalkulator', 'egipt', 'pachołek', 'berło', 'dyskoteka', 'tabletka', 'orkiestra', 'kłótnia', 'butelka', 'szminka', 'pęcherz', 'podpórka',
    'traktor', 'kostium kąpielowy', 'głowa domu', 'złodziej czasu', 'ptak', 'kalosze', 'kropidło', 'morze czarne', 'pięściarz', 'dynamo', 'cyfra',
    'alpinista', 'pluć sobie w brodę', 'bałagan', 'łamigłówka', 'trumna', 'ruchome schody', 'lizak', 'pół litra', 'słuchacz', 'slalom',
    'czarna porzeczka', 'film animowany', 'ogórek', 'mama', 'tata', 'awantura', 'falbanka', 'kotwica', 'tablica ogłoszeń', 'ocean',
    'czekolada z orzechami', 'nadajnik', 'slipy', 'spadochroniarz', 'kura domowa', 'parafia', 'ulewa', 'parkiet', 'egoista', 'sędzia kalosz',
    'myjnia', 'górka', 'krok naprzód', 'martwa natura', 'kształt', 'krawężnik', 'kasa chorych', 'tabliczka', 'dach nad głową', 'kangur',
    'przystanek', 'jelito grube', 'lotnik', 'wulkan', 'spodnie', 'rachunek za telefon', 'skuter śnieżny', 'linijka', 'apteczka', 'świeca',
    'miesiąc miodowy', 'mięso armatnie', 'rentgen', 'kaskader', 'ruina', 'mundur', 'wisienka na torcie', 'kod pocztowy', 'słonecznik', 'biel',
    'sanki', 'wysokość', 'molo', 'błąd', 'rzucić okiem', 'turysta', 'okręt', 'studnia', 'karabin maszynowy', 'klaps', 'dziura zabita dechami',
    'gwarancja', 'model', 'trop', 'lont', 'ogon', 'kołdra', 'koc', 'ruletka', 'motorówka', 'absolwent', 'wyścig z czasem', 'lanie', 'akapit', 'ogród',
    'zając', 'bobas', 'przeszczep', 'stolik', 'przejście podziemne', 'bunt', 'wtyczka', 'biały murzyn', 'plomba', 'pantofel', 'podłoga', 'wianek',
    'oberwanie chmury', 'podkładka', 'paciorek', 'dmuchawiec', 'rzucać słowa na wiatr', 'figura', 'miłość', 'rekin', 'tunel', 'laska',
    'latający dywan', 'papier ścierny', 'skup metali', 'zasłona dymna', 'klasztor', 'słoń', 'kiełbasa', 'wiertło', 'ciężarek', 'forsa', 'klepsydra',
    'stopka', 'szczyt', 'zakaz', 'nakaz', 'osiedle', 'zabijać czas', 'marionetka', 'złota myśl', 'pasztet', 'platforma', 'browar', 'kij golfowy',
    'album', 'naklejka', 'klatka piersiowa', 'jarmark', 'dzban', 'amator', 'kryptowaluta', 'mały fiat', 'arena', 'krok', 'trojaczki', 'omlet',
    'żarówka', 'objazd', 'agrest', 'opona', 'pinokio', 'kasztan', 'lodowisko', 'gracz', 'horoskop', 'hurtownia', 'cisza', 'laser', 'ćwiartka',
    'modlitwa', 'lusterko', 'ciąża', 'czoło', 'wędkarz', 'powieka', 'kieliszek', 'paleta', 'kaseta', 'portfel', 'kamera', 'benzyna', 'szyna',
    'worek na śmieci', 'wymioty', 'pierwszy ruch', 'schody', 'zebra', 'odznaka', 'pieszy', 'gwóźdź', 'cztery ściany', 'balon', 'frytki', 'hydrant',
    'rzut karny', 'apetyt', 'bakteria', 'terrorysta', 'antyterrorysta', 'trampolina', 'motyka', 'ul', 'zapora', 'jeleń', 'sarna', 'piramida', 'kokarda',
    'przynęta', 'przeciąg', 'pszczoła', 'ściana', 'tęcza', 'uchwyt', 'dyktafon', 'chlew', 'kolejka', 'miś uszatek', 'korona', 'złomowisko',
    'zakaz wjazdu', 'piwo bezalkoholowe', 'pochylnia', 'sztanga', 'guma do żucia', 'herb', 'jagoda', 'przesiadka', 'żyletka', 'dotyk',
    'jasny gwint', 'znicz', 'sejf', 'awaria', 'guzik', 'rycerz', 'poczta', 'powrót', 'barman', 'kominiarka', 'obiektyw', 'łokieć', 'promień',
    'zawleczka', 'futryna', 'korytarz', 'gej', 'dół rzeki', 'ułamek', 'rękawica', 'warcaby', 'szachy', 'oryginał', 'wagary', 'pokarm', 'ster',
    'złota rączka', 'piłkarz', 'waga', 'koralik', 'szkielet', 'obrót', 'dom dla lalek', 'bydło', 'herbata', 'koks', 'poziom', 'rzut rożny',
    'pan młody', 'iskra', 'ryba', 'konserwa', 'pisanka', 'dokument', 'głowa', 'papier', 'widelec', 'pomoc drogowa', 'plagiat', 'kosmita', 'sznurek',
    'widły', 'grzyb', 'pokemon', 'hałas', 'meble', 'koktajl mołotowa', 'bogacz', 'zakaz jazdy na rolkach', 'spać na pieniądzach', 'medal',
    'krótka piłka', 'grzywka', 'napoje chłodzące', 'kielich', 'podkładka', 'fotomontaż', 'pudzian', 'spacja', 'ulewa', 'chwast', 'hejnał mariacki',
    'znaczek', 'ciepło', 'nacięcie', 'gaduła', 'beczka śmiechu', 'pisarz', 'dostać kosza', 'nakrętka', 'białe plamy', 'truskawka', 'halogen',
    'bawić się w kotka i myszkę', 'zupa', 'rycerz', 'dowcip', 'łysa opona', 'packa', 'stan nieważkości', 'harfa', 'budowla', 'kaganiec', 'ambona',
    'wsadzić koj w mrowisko', 'bomba', 'panna młoda', 'pan młody', 'czarny koń', 'karmnik', 'plaża nudystów', 'najeść się strachu', 'zakład pogrzebowy',
    'transparent', 'wieża kontroli lotów', 'rurka z bitą śmietaną', 'punkt skupu butelek', 'barwa', 'znicz', 'wróbel w garści', 'bunt', 'pisklę',
    'podnosić poprzeczkę', 'bilans', 'ekwipunek', 'zagadka', 'dmuchać na zimne', 'bizuteria', 'naleśnik', 'gąbka', 'ciało niebieski', 'śmierdzące jajko',
    'paczkomat', 'wino kobiety i śpiew', 'opatrunek', 'loteria', 'linia wysokiego napięcia', 'osoba toważysząca', 'Zdrowie', 'poszukiwany',
    'stary piernik', 'czarna dziura', 'nawigacja', 'film dla dorosłych', 'garnek', 'cztery pory roku', 'niedziela', 'VIP', 'laba', 'narcyz',
    'loża szyderców', 'konik na biegunach', 'strona internetowa', 'kod kreskowy', 'osioł', 'przedmieście', 'woda utleniona', 'przekleństwo',
    'samouczek', 'książka telefoniczna', 'titanic', 'święty mikołaj', 'formuła jeden', 'zimne piwko', 'ania z zielonego wzgorza', 'rumcajs',
    'wakacyjna przygoda', 'zaproszenie', 'krzesło', 'waga', 'ambrozja', 'wróg', 'różowe okulary', 'iluzjonista', 'rachunek sumienia', 'bańki mydlane',
    'ostatnia godzina', 'panda', 'koala', 'wróżbita', 'lunatyk', 'młot pneumatyczny', 'tabernakulum', 'zamki z piasku', 'origami', 'gra planszowa',
    'karuzela', 'lekcja', 'huśtawka', 'antywirus', 'spadochron', 'oranżada', 'zapasy', 'sumo', 'posłowie', 'sami swoi', 'matematyka matką nauk',
    'przychodnia', 'szpital', 'stół szwedzki', 'członek', 'kawior', 'literatura', 'występ', 'barbórka', 'noworodek', 'szybcy i wściekli', 'enigma',
    'informatyk', 'salami', 'wieczór kawalerski', 'wycieczka szkolna', 'złote góry', 'płyta', 'topienie marzanny', 'zakupy', 'zbiór zadań',
    'kopciuszek', 'gips', 'ciało stałe', 'baton', 'monitor', 'stuknij się w łeb', 'prosiaczek', 'klisza', 'głuchy telefon', 'malowana lala',
    'okno plastikowe', 'margines społeczny', 'oczy piwne', 'palma', 'studniówka', 'niebo w gębie', 'szklana pułapka', 'alaska', 'akta', 'pojutrze',
    'katar', 'jemioła', 'zmywacz do paznokci', 'sztuczna inteligencja', 'joker', 'poziomka', 'sex', 'fotografia', 'aniołek', 'karabin', 'zło', 'żylaki',
    'piotruś pan', 'niebezpieczeństwo', 'liceum', 'faraon', 'technikum', 'sąsiad', 'uniwersytet', 'trucht', 'magazynier', 'jaś fasola', 'puszcza',
];